# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/18191/Desktop/Lab14/Lab14.srcs/sources_1/ip/Driver_MIPI0_0_1/Driver_MIPI0_0.xci
# IP: The module: 'Driver_MIPI0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/18191/Desktop/Lab14/Lab14.srcs/sources_1/ip/Driver_MIPI0_0_1/src/csi_to_axis_0/csi_to_axis_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==csi_to_axis_0 || ORIG_REF_NAME==csi_to_axis_0} -quiet] -quiet

# IP: c:/Users/18191/Desktop/Lab14/Lab14.srcs/sources_1/ip/Driver_MIPI0_0_1/src/csi2_d_phy_rx_0/csi2_d_phy_rx_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==csi2_d_phy_rx_0 || ORIG_REF_NAME==csi2_d_phy_rx_0} -quiet] -quiet

# IP: c:/Users/18191/Desktop/Lab14/Lab14.srcs/sources_1/ip/Driver_MIPI0_0_1/src/blk_mem_gen_0/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: c:/Users/18191/Desktop/Lab14/Lab14.srcs/sources_1/ip/Driver_MIPI0_0_1/src/csi_to_axis_0/hdl/csi_to_axis.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==csi_to_axis_0 || ORIG_REF_NAME==csi_to_axis_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/18191/Desktop/Lab14/Lab14.srcs/sources_1/ip/Driver_MIPI0_0_1/src/csi2_d_phy_rx_0/hdl/csi2_d_phy_rx.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==csi2_d_phy_rx_0 || ORIG_REF_NAME==csi2_d_phy_rx_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/18191/Desktop/Lab14/Lab14.srcs/sources_1/ip/Driver_MIPI0_0_1/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# IP: c:/Users/18191/Desktop/Lab14/Lab14.srcs/sources_1/ip/Driver_MIPI0_0_1/Driver_MIPI0_0.xci
# IP: The module: 'Driver_MIPI0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/18191/Desktop/Lab14/Lab14.srcs/sources_1/ip/Driver_MIPI0_0_1/src/csi_to_axis_0/csi_to_axis_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==csi_to_axis_0 || ORIG_REF_NAME==csi_to_axis_0} -quiet] -quiet

# IP: c:/Users/18191/Desktop/Lab14/Lab14.srcs/sources_1/ip/Driver_MIPI0_0_1/src/csi2_d_phy_rx_0/csi2_d_phy_rx_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==csi2_d_phy_rx_0 || ORIG_REF_NAME==csi2_d_phy_rx_0} -quiet] -quiet

# IP: c:/Users/18191/Desktop/Lab14/Lab14.srcs/sources_1/ip/Driver_MIPI0_0_1/src/blk_mem_gen_0/blk_mem_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: c:/Users/18191/Desktop/Lab14/Lab14.srcs/sources_1/ip/Driver_MIPI0_0_1/src/csi_to_axis_0/hdl/csi_to_axis.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==csi_to_axis_0 || ORIG_REF_NAME==csi_to_axis_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/18191/Desktop/Lab14/Lab14.srcs/sources_1/ip/Driver_MIPI0_0_1/src/csi2_d_phy_rx_0/hdl/csi2_d_phy_rx.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==csi2_d_phy_rx_0 || ORIG_REF_NAME==csi2_d_phy_rx_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/18191/Desktop/Lab14/Lab14.srcs/sources_1/ip/Driver_MIPI0_0_1/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
