# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/system.xdc

# IP: ip/Driver_IIC_0_1/Driver_IIC_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Driver_IIC_0 || ORIG_REF_NAME==Driver_IIC_0} -quiet] -quiet

# IP: ip/Driver_MIPI_0_1/Driver_MIPI_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Driver_MIPI_0 || ORIG_REF_NAME==Driver_MIPI_0} -quiet] -quiet
